/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AppRouteImport } from './routes/app'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellActivitiesRouteImport } from './routes/_shell/activities'
import { Route as ShellAgentsRouteImport } from './routes/_shell/agents'
import { Route as ShellApiReferenceRouteImport } from './routes/_shell/api-reference'
import { Route as ShellPlaygroundRouteImport } from './routes/_shell/playground'
import { Route as ShellTryRouteImport } from './routes/_shell/try'
import { Route as AppSplatRouteImport } from './routes/app/$'
import { Route as ShellModelsIndexRouteImport } from './routes/_shell/models/index'
import { Route as ShellModelsSlugRouteImport } from './routes/_shell/models/$slug'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellActivitiesRoute = ShellActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAgentsRoute = ShellAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => ShellRoute,
} as any)
const ShellApiReferenceRoute = ShellApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPlaygroundRoute = ShellPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => ShellRoute,
} as any)
const ShellTryRoute = ShellTryRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => ShellRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRoute,
} as any)
const ShellModelsIndexRoute = ShellModelsIndexRouteImport.update({
  id: '/models/',
  path: '/models/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModelsSlugRoute = ShellModelsSlugRouteImport.update({
  id: '/models/$slug',
  path: '/models/$slug',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/app': typeof AppRouteWithChildren
  '/activities': typeof ShellActivitiesRoute
  '/agents': typeof ShellAgentsRoute
  '/api-reference': typeof ShellApiReferenceRoute
  '/playground': typeof ShellPlaygroundRoute
  '/try': typeof ShellTryRoute
  '/app/$': typeof AppSplatRoute
  '/models/$slug': typeof ShellModelsSlugRoute
  '/models/': typeof ShellModelsIndexRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteWithChildren
  '/activities': typeof ShellActivitiesRoute
  '/agents': typeof ShellAgentsRoute
  '/api-reference': typeof ShellApiReferenceRoute
  '/playground': typeof ShellPlaygroundRoute
  '/try': typeof ShellTryRoute
  '/app/$': typeof AppSplatRoute
  '/': typeof ShellIndexRoute
  '/models/$slug': typeof ShellModelsSlugRoute
  '/models': typeof ShellModelsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/_shell/activities': typeof ShellActivitiesRoute
  '/_shell/agents': typeof ShellAgentsRoute
  '/_shell/api-reference': typeof ShellApiReferenceRoute
  '/_shell/playground': typeof ShellPlaygroundRoute
  '/_shell/try': typeof ShellTryRoute
  '/app/$': typeof AppSplatRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/models/$slug': typeof ShellModelsSlugRoute
  '/_shell/models/': typeof ShellModelsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/activities'
    | '/agents'
    | '/api-reference'
    | '/playground'
    | '/try'
    | '/app/$'
    | '/models/$slug'
    | '/models/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/activities'
    | '/agents'
    | '/api-reference'
    | '/playground'
    | '/try'
    | '/app/$'
    | '/'
    | '/models/$slug'
    | '/models'
  id:
    | '__root__'
    | '/_shell'
    | '/app'
    | '/_shell/activities'
    | '/_shell/agents'
    | '/_shell/api-reference'
    | '/_shell/playground'
    | '/_shell/try'
    | '/app/$'
    | '/_shell/'
    | '/_shell/models/$slug'
    | '/_shell/models/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/activities': {
      id: '/_shell/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ShellActivitiesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/agents': {
      id: '/_shell/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof ShellAgentsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/api-reference': {
      id: '/_shell/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ShellApiReferenceRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/playground': {
      id: '/_shell/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof ShellPlaygroundRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/try': {
      id: '/_shell/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof ShellTryRouteImport
      parentRoute: typeof ShellRoute
    }
    '/app/$': {
      id: '/app/$'
      path: '/$'
      fullPath: '/app/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_shell/models/': {
      id: '/_shell/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof ShellModelsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/models/$slug': {
      id: '/_shell/models/$slug'
      path: '/models/$slug'
      fullPath: '/models/$slug'
      preLoaderRoute: typeof ShellModelsSlugRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellActivitiesRoute: typeof ShellActivitiesRoute
  ShellAgentsRoute: typeof ShellAgentsRoute
  ShellApiReferenceRoute: typeof ShellApiReferenceRoute
  ShellPlaygroundRoute: typeof ShellPlaygroundRoute
  ShellTryRoute: typeof ShellTryRoute
  ShellIndexRoute: typeof ShellIndexRoute
  ShellModelsSlugRoute: typeof ShellModelsSlugRoute
  ShellModelsIndexRoute: typeof ShellModelsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellActivitiesRoute: ShellActivitiesRoute,
  ShellAgentsRoute: ShellAgentsRoute,
  ShellApiReferenceRoute: ShellApiReferenceRoute,
  ShellPlaygroundRoute: ShellPlaygroundRoute,
  ShellTryRoute: ShellTryRoute,
  ShellIndexRoute: ShellIndexRoute,
  ShellModelsSlugRoute: ShellModelsSlugRoute,
  ShellModelsIndexRoute: ShellModelsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

interface AppRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSplatRoute: AppSplatRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
